import type { SubmissionFormSchema } from "./submission-form-schema";
import { DEFAULT_FORM_PRESENTATION } from "./submission-form-schema";

export const DEFAULT_FORM_SCHEMA: SubmissionFormSchema = {
  schemaVersion: 2,
  layout: "single_page",
  introduction:
    "Share a practical session that gives attendees something useful to take away.",
  presentation: DEFAULT_FORM_PRESENTATION,
  sections: [
    {
      id: "proposal",
      title: "Session proposal",
      description: "Tell us what you want to share with attendees.",
    },
  ],
  fields: [
    {
      sectionId: "proposal",
      id: "title",
      label: "Session title",
      type: "short_text",
      required: true,
      help: "Use a clear, attendee-focused title.",
      example: "How a small programme team removed three weeks of manual work",
      options: [],
      reviewVisibility: "reviewers",
      blindReviewVisibility: "content",
      condition: null,
    },
    {
      sectionId: "proposal",
      id: "description",
      label: "Session description",
      type: "long_text",
      required: true,
      help: "What will attendees learn?",
      example:
        "Describe the problem, what you tried, the outcome and what attendees can apply themselves.",
      options: [],
      reviewVisibility: "reviewers",
      blindReviewVisibility: "content",
      condition: null,
    },
    {
      sectionId: "proposal",
      id: "category",
      label: "Tracks",
      type: "multi_select",
      required: true,
      help: "Choose every programme track this proposal should be reviewed for.",
      example: "",
      options: ["AI & Innovation", "Event Operations", "Experience Design"],
      reviewVisibility: "reviewers",
      blindReviewVisibility: "content",
      condition: null,
    },
    {
      sectionId: "proposal",
      id: "format",
      label: "Format",
      type: "select",
      required: true,
      help: "",
      example: "",
      options: ["Workshop", "Presentation", "Panel", "Keynote"],
      reviewVisibility: "reviewers",
      blindReviewVisibility: "content",
      condition: null,
    },
    {
      sectionId: "proposal",
      id: "materials",
      label: "Materials and room setup",
      type: "long_text",
      required: true,
      help: "List any equipment or setup required.",
      example: "Moveable tables, a projector and space for groups of six.",
      options: [],
      reviewVisibility: "reviewers",
      blindReviewVisibility: "content",
      condition: { fieldId: "format", equals: "Workshop" },
    },
    {
      sectionId: "proposal",
      id: "video",
      label: "Optional pitch video",
      type: "video",
      required: false,
      help: "Upload an MP4/WebM file or link to a private or unlisted HTTPS video.",
      example: "",
      options: [],
      reviewVisibility: "reviewers",
      blindReviewVisibility: "content",
      condition: null,
    },
  ],
};
