import { readFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';
import { submissions, rubric, scheduleSessions, rooms, tasks, programmeSessions, integrations } from '../public/seed.js';
import { calculateWeightedReview } from '../src/domain/review.mjs';
import { detectSpeakerConflicts, validateScheduleMove } from '../src/domain/schedule.mjs';
import { calculateWeightedReadiness } from '../src/domain/readiness.mjs';

const required = ['public/index.html','public/styles.css','public/app.js','public/seed.js','README.md','wrangler.jsonc'];
for (const path of required) await access(new URL(`../${path}`, import.meta.url), constants.R_OK);
const app = await readFile(new URL('../public/app.js', import.meta.url), 'utf8');
const routes = ['commandPage','eventPage','submissionsPage','reviewPage','formBuilderPage','speakersPage','schedulePage','communicationsPage','tasksPage','programmeAdminPage','integrationsPage','settingsPage','assistantPage','speakerDashboardPage','speakerResourcesPage','publicProgrammePage','applyPage','render'];
for (const route of routes) if (!app.includes(`function ${route}(`)) throw new Error(`Missing demo route function: ${route}`);
if (submissions.length < 6) throw new Error('Seed data must include representative review volume.');
if (tasks.length < 6) throw new Error('Seed data must include representative readiness tasks.');
if (programmeSessions.length < 5) throw new Error('Seed programme is incomplete.');
if (integrations.length !== 5) throw new Error('Demo must show exactly five connected integrations.');
const score = calculateWeightedReview(rubric);
if (score.score !== 4.25) throw new Error(`Unexpected seeded review score: ${score.score}`);
const conflicts = detectSpeakerConflicts(scheduleSessions);
if (!conflicts.some(([a,b]) => new Set([a,b]).has('s10') && new Set([a,b]).has('s11'))) throw new Error('Expected Jamie Lee conflict is missing.');
const move = validateScheduleMove({sessions:scheduleSessions,rooms,movingId:'s10',room:'303',start:840,end:900,trackConflictPolicy:'warn'});
if (move.valid) throw new Error('Seed data incorrectly claims the 2:00 PM move is safe; it overlaps Emerging Trends until 2:15 PM.');
const validMove = validateScheduleMove({sessions:scheduleSessions,rooms,movingId:'s10',room:'303',start:855,end:915,trackConflictPolicy:'warn'});
if (!validMove.valid) throw new Error(`Expected 2:15 PM move to be safe: ${validMove.reasons.join(' ')}`);
const readiness = calculateWeightedReadiness(tasks);
if (!Number.isFinite(readiness)) throw new Error('Readiness calculation failed.');
console.log(JSON.stringify({routes:routes.length,submissions:submissions.length,tasks:tasks.length,programme:programmeSessions.length,integrations:integrations.length,reviewScore:score.score,weightedReadiness:readiness},null,2));
